/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.61.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package iris.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets CaseIdentificationSource
 */
public enum CaseIdentificationSource {
  UNKNOWN("UNKNOWN"),
  OUTBREAK_INVESTIGATION("OUTBREAK_INVESTIGATION"),
  CONTACT_TRACKING_APP("CONTACT_TRACKING_APP"),
  SUSPICION_REPORT("SUSPICION_REPORT"),
  CONTACT_TRACING("CONTACT_TRACING"),
  SCREENING("SCREENING"),
  OTHER("OTHER");

  private String value;

  CaseIdentificationSource(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CaseIdentificationSource fromValue(String text) {
    for (CaseIdentificationSource b : CaseIdentificationSource.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
