/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.61.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package iris.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import iris.sormas.client.model.ResponsibleJurisdictionDto;
/**
 * CaseJurisdictionDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-08T06:53:38.737461+02:00[Europe/Berlin]")
public class CaseJurisdictionDto {
  @JsonProperty("reportingUserUuid")
  private String reportingUserUuid = null;

  @JsonProperty("responsibleJurisdiction")
  private ResponsibleJurisdictionDto responsibleJurisdiction = null;

  @JsonProperty("regionUuid")
  private String regionUuid = null;

  @JsonProperty("districtUuid")
  private String districtUuid = null;

  @JsonProperty("communityUuid")
  private String communityUuid = null;

  @JsonProperty("healthFacilityUuid")
  private String healthFacilityUuid = null;

  @JsonProperty("pointOfEntryUuid")
  private String pointOfEntryUuid = null;

  public CaseJurisdictionDto reportingUserUuid(String reportingUserUuid) {
    this.reportingUserUuid = reportingUserUuid;
    return this;
  }

   /**
   * Get reportingUserUuid
   * @return reportingUserUuid
  **/
  @Schema(description = "")
  public String getReportingUserUuid() {
    return reportingUserUuid;
  }

  public void setReportingUserUuid(String reportingUserUuid) {
    this.reportingUserUuid = reportingUserUuid;
  }

  public CaseJurisdictionDto responsibleJurisdiction(ResponsibleJurisdictionDto responsibleJurisdiction) {
    this.responsibleJurisdiction = responsibleJurisdiction;
    return this;
  }

   /**
   * Get responsibleJurisdiction
   * @return responsibleJurisdiction
  **/
  @Schema(description = "")
  public ResponsibleJurisdictionDto getResponsibleJurisdiction() {
    return responsibleJurisdiction;
  }

  public void setResponsibleJurisdiction(ResponsibleJurisdictionDto responsibleJurisdiction) {
    this.responsibleJurisdiction = responsibleJurisdiction;
  }

  public CaseJurisdictionDto regionUuid(String regionUuid) {
    this.regionUuid = regionUuid;
    return this;
  }

   /**
   * Get regionUuid
   * @return regionUuid
  **/
  @Schema(description = "")
  public String getRegionUuid() {
    return regionUuid;
  }

  public void setRegionUuid(String regionUuid) {
    this.regionUuid = regionUuid;
  }

  public CaseJurisdictionDto districtUuid(String districtUuid) {
    this.districtUuid = districtUuid;
    return this;
  }

   /**
   * Get districtUuid
   * @return districtUuid
  **/
  @Schema(description = "")
  public String getDistrictUuid() {
    return districtUuid;
  }

  public void setDistrictUuid(String districtUuid) {
    this.districtUuid = districtUuid;
  }

  public CaseJurisdictionDto communityUuid(String communityUuid) {
    this.communityUuid = communityUuid;
    return this;
  }

   /**
   * Get communityUuid
   * @return communityUuid
  **/
  @Schema(description = "")
  public String getCommunityUuid() {
    return communityUuid;
  }

  public void setCommunityUuid(String communityUuid) {
    this.communityUuid = communityUuid;
  }

  public CaseJurisdictionDto healthFacilityUuid(String healthFacilityUuid) {
    this.healthFacilityUuid = healthFacilityUuid;
    return this;
  }

   /**
   * Get healthFacilityUuid
   * @return healthFacilityUuid
  **/
  @Schema(description = "")
  public String getHealthFacilityUuid() {
    return healthFacilityUuid;
  }

  public void setHealthFacilityUuid(String healthFacilityUuid) {
    this.healthFacilityUuid = healthFacilityUuid;
  }

  public CaseJurisdictionDto pointOfEntryUuid(String pointOfEntryUuid) {
    this.pointOfEntryUuid = pointOfEntryUuid;
    return this;
  }

   /**
   * Get pointOfEntryUuid
   * @return pointOfEntryUuid
  **/
  @Schema(description = "")
  public String getPointOfEntryUuid() {
    return pointOfEntryUuid;
  }

  public void setPointOfEntryUuid(String pointOfEntryUuid) {
    this.pointOfEntryUuid = pointOfEntryUuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseJurisdictionDto caseJurisdictionDto = (CaseJurisdictionDto) o;
    return Objects.equals(this.reportingUserUuid, caseJurisdictionDto.reportingUserUuid) &&
        Objects.equals(this.responsibleJurisdiction, caseJurisdictionDto.responsibleJurisdiction) &&
        Objects.equals(this.regionUuid, caseJurisdictionDto.regionUuid) &&
        Objects.equals(this.districtUuid, caseJurisdictionDto.districtUuid) &&
        Objects.equals(this.communityUuid, caseJurisdictionDto.communityUuid) &&
        Objects.equals(this.healthFacilityUuid, caseJurisdictionDto.healthFacilityUuid) &&
        Objects.equals(this.pointOfEntryUuid, caseJurisdictionDto.pointOfEntryUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportingUserUuid, responsibleJurisdiction, regionUuid, districtUuid, communityUuid, healthFacilityUuid, pointOfEntryUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseJurisdictionDto {\n");
    
    sb.append("    reportingUserUuid: ").append(toIndentedString(reportingUserUuid)).append("\n");
    sb.append("    responsibleJurisdiction: ").append(toIndentedString(responsibleJurisdiction)).append("\n");
    sb.append("    regionUuid: ").append(toIndentedString(regionUuid)).append("\n");
    sb.append("    districtUuid: ").append(toIndentedString(districtUuid)).append("\n");
    sb.append("    communityUuid: ").append(toIndentedString(communityUuid)).append("\n");
    sb.append("    healthFacilityUuid: ").append(toIndentedString(healthFacilityUuid)).append("\n");
    sb.append("    pointOfEntryUuid: ").append(toIndentedString(pointOfEntryUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
