/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.61.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package iris.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * EventParticipantJurisdictionDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-08T06:53:38.737461+02:00[Europe/Berlin]")
public class EventParticipantJurisdictionDto {
  @JsonProperty("eventParticipantUuid")
  private String eventParticipantUuid = null;

  @JsonProperty("reportingUserUuid")
  private String reportingUserUuid = null;

  @JsonProperty("regionUuid")
  private String regionUuid = null;

  @JsonProperty("districtUuid")
  private String districtUuid = null;

  @JsonProperty("eventUuid")
  private String eventUuid = null;

  public EventParticipantJurisdictionDto eventParticipantUuid(String eventParticipantUuid) {
    this.eventParticipantUuid = eventParticipantUuid;
    return this;
  }

   /**
   * Get eventParticipantUuid
   * @return eventParticipantUuid
  **/
  @Schema(description = "")
  public String getEventParticipantUuid() {
    return eventParticipantUuid;
  }

  public void setEventParticipantUuid(String eventParticipantUuid) {
    this.eventParticipantUuid = eventParticipantUuid;
  }

  public EventParticipantJurisdictionDto reportingUserUuid(String reportingUserUuid) {
    this.reportingUserUuid = reportingUserUuid;
    return this;
  }

   /**
   * Get reportingUserUuid
   * @return reportingUserUuid
  **/
  @Schema(description = "")
  public String getReportingUserUuid() {
    return reportingUserUuid;
  }

  public void setReportingUserUuid(String reportingUserUuid) {
    this.reportingUserUuid = reportingUserUuid;
  }

  public EventParticipantJurisdictionDto regionUuid(String regionUuid) {
    this.regionUuid = regionUuid;
    return this;
  }

   /**
   * Get regionUuid
   * @return regionUuid
  **/
  @Schema(description = "")
  public String getRegionUuid() {
    return regionUuid;
  }

  public void setRegionUuid(String regionUuid) {
    this.regionUuid = regionUuid;
  }

  public EventParticipantJurisdictionDto districtUuid(String districtUuid) {
    this.districtUuid = districtUuid;
    return this;
  }

   /**
   * Get districtUuid
   * @return districtUuid
  **/
  @Schema(description = "")
  public String getDistrictUuid() {
    return districtUuid;
  }

  public void setDistrictUuid(String districtUuid) {
    this.districtUuid = districtUuid;
  }

  public EventParticipantJurisdictionDto eventUuid(String eventUuid) {
    this.eventUuid = eventUuid;
    return this;
  }

   /**
   * Get eventUuid
   * @return eventUuid
  **/
  @Schema(description = "")
  public String getEventUuid() {
    return eventUuid;
  }

  public void setEventUuid(String eventUuid) {
    this.eventUuid = eventUuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventParticipantJurisdictionDto eventParticipantJurisdictionDto = (EventParticipantJurisdictionDto) o;
    return Objects.equals(this.eventParticipantUuid, eventParticipantJurisdictionDto.eventParticipantUuid) &&
        Objects.equals(this.reportingUserUuid, eventParticipantJurisdictionDto.reportingUserUuid) &&
        Objects.equals(this.regionUuid, eventParticipantJurisdictionDto.regionUuid) &&
        Objects.equals(this.districtUuid, eventParticipantJurisdictionDto.districtUuid) &&
        Objects.equals(this.eventUuid, eventParticipantJurisdictionDto.eventUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventParticipantUuid, reportingUserUuid, regionUuid, districtUuid, eventUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventParticipantJurisdictionDto {\n");
    
    sb.append("    eventParticipantUuid: ").append(toIndentedString(eventParticipantUuid)).append("\n");
    sb.append("    reportingUserUuid: ").append(toIndentedString(reportingUserUuid)).append("\n");
    sb.append("    regionUuid: ").append(toIndentedString(regionUuid)).append("\n");
    sb.append("    districtUuid: ").append(toIndentedString(districtUuid)).append("\n");
    sb.append("    eventUuid: ").append(toIndentedString(eventUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
