/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.61.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package iris.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets FacilityTypeGroup
 */
public enum FacilityTypeGroup {
  ACCOMMODATION("ACCOMMODATION"),
  CARE_FACILITY("CARE_FACILITY"),
  CATERING_OUTLET("CATERING_OUTLET"),
  EDUCATIONAL_FACILITY("EDUCATIONAL_FACILITY"),
  LEISURE_FACILITY("LEISURE_FACILITY"),
  MEDICAL_FACILITY("MEDICAL_FACILITY"),
  WORKING_PLACE("WORKING_PLACE"),
  RESIDENCE("RESIDENCE"),
  COMMERCE("COMMERCE");

  private String value;

  FacilityTypeGroup(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static FacilityTypeGroup fromValue(String text) {
    for (FacilityTypeGroup b : FacilityTypeGroup.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
