/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.61.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package iris.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import iris.sormas.client.model.PointOfEntryType;
/**
 * PointOfEntryReferenceDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-08T06:53:38.737461+02:00[Europe/Berlin]")
public class PointOfEntryReferenceDto {
  @JsonProperty("uuid")
  private String uuid = null;

  @JsonProperty("caption")
  private String caption = null;

  @JsonProperty("externalId")
  private String externalId = null;

  @JsonProperty("pointOfEntryType")
  private PointOfEntryType pointOfEntryType = null;

  @JsonProperty("otherPointOfEntry")
  private Boolean otherPointOfEntry = null;

  public PointOfEntryReferenceDto uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @Schema(required = true, description = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public PointOfEntryReferenceDto caption(String caption) {
    this.caption = caption;
    return this;
  }

   /**
   * Get caption
   * @return caption
  **/
  @Schema(description = "")
  public String getCaption() {
    return caption;
  }

  public void setCaption(String caption) {
    this.caption = caption;
  }

  public PointOfEntryReferenceDto externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @Schema(description = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public PointOfEntryReferenceDto pointOfEntryType(PointOfEntryType pointOfEntryType) {
    this.pointOfEntryType = pointOfEntryType;
    return this;
  }

   /**
   * Get pointOfEntryType
   * @return pointOfEntryType
  **/
  @Schema(description = "")
  public PointOfEntryType getPointOfEntryType() {
    return pointOfEntryType;
  }

  public void setPointOfEntryType(PointOfEntryType pointOfEntryType) {
    this.pointOfEntryType = pointOfEntryType;
  }

  public PointOfEntryReferenceDto otherPointOfEntry(Boolean otherPointOfEntry) {
    this.otherPointOfEntry = otherPointOfEntry;
    return this;
  }

   /**
   * Get otherPointOfEntry
   * @return otherPointOfEntry
  **/
  @Schema(description = "")
  public Boolean isOtherPointOfEntry() {
    return otherPointOfEntry;
  }

  public void setOtherPointOfEntry(Boolean otherPointOfEntry) {
    this.otherPointOfEntry = otherPointOfEntry;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PointOfEntryReferenceDto pointOfEntryReferenceDto = (PointOfEntryReferenceDto) o;
    return Objects.equals(this.uuid, pointOfEntryReferenceDto.uuid) &&
        Objects.equals(this.caption, pointOfEntryReferenceDto.caption) &&
        Objects.equals(this.externalId, pointOfEntryReferenceDto.externalId) &&
        Objects.equals(this.pointOfEntryType, pointOfEntryReferenceDto.pointOfEntryType) &&
        Objects.equals(this.otherPointOfEntry, pointOfEntryReferenceDto.otherPointOfEntry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, caption, externalId, pointOfEntryType, otherPointOfEntry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PointOfEntryReferenceDto {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    caption: ").append(toIndentedString(caption)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    pointOfEntryType: ").append(toIndentedString(pointOfEntryType)).append("\n");
    sb.append("    otherPointOfEntry: ").append(toIndentedString(otherPointOfEntry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
