/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.61.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package iris.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ScreeningType
 */
public enum ScreeningType {
  ON_HOSPITAL_ADMISSION("ON_HOSPITAL_ADMISSION"),
  ON_CARE_HOME_ADMISSION("ON_CARE_HOME_ADMISSION"),
  ON_ASYLUM_ADMISSION("ON_ASYLUM_ADMISSION"),
  ON_ENTRY_FROM_RISK_AREA("ON_ENTRY_FROM_RISK_AREA"),
  HEALTH_SECTOR_EMPLOYEE("HEALTH_SECTOR_EMPLOYEE"),
  EDUCATIONAL_INSTITUTIONS("EDUCATIONAL_INSTITUTIONS"),
  SELF_ARRANGED_TEST("SELF_ARRANGED_TEST"),
  SELF_CONDUCTED_TEST("SELF_CONDUCTED_TEST"),
  OTHER("OTHER");

  private String value;

  ScreeningType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ScreeningType fromValue(String text) {
    for (ScreeningType b : ScreeningType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
