/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.61.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package iris.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import iris.sormas.client.model.Vaccination;
import iris.sormas.client.model.VaccinationInfoSource;
import iris.sormas.client.model.Vaccine;
import iris.sormas.client.model.VaccineManufacturer;
import java.time.OffsetDateTime;
import java.time.Instant;
/**
 * VaccinationInfoDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-08T06:53:38.737461+02:00[Europe/Berlin]")
public class VaccinationInfoDto {
  @JsonProperty("creationDate")
  private Instant creationDate = null;

  @JsonProperty("changeDate")
  private Instant changeDate = null;

  @JsonProperty("uuid")
  private String uuid = null;

  @JsonProperty("vaccination")
  private Vaccination vaccination = null;

  @JsonProperty("vaccinationDoses")
  private String vaccinationDoses = null;

  @JsonProperty("firstVaccinationDate")
  private Instant firstVaccinationDate = null;

  @JsonProperty("lastVaccinationDate")
  private Instant lastVaccinationDate = null;

  @JsonProperty("vaccinationInfoSource")
  private VaccinationInfoSource vaccinationInfoSource = null;

  @JsonProperty("vaccineName")
  private Vaccine vaccineName = null;

  @JsonProperty("otherVaccineName")
  private String otherVaccineName = null;

  @JsonProperty("vaccineManufacturer")
  private VaccineManufacturer vaccineManufacturer = null;

  @JsonProperty("otherVaccineManufacturer")
  private String otherVaccineManufacturer = null;

  @JsonProperty("vaccineInn")
  private String vaccineInn = null;

  @JsonProperty("vaccineBatchNumber")
  private String vaccineBatchNumber = null;

  @JsonProperty("vaccineUniiCode")
  private String vaccineUniiCode = null;

  @JsonProperty("vaccineAtcCode")
  private String vaccineAtcCode = null;

  public VaccinationInfoDto creationDate(Instant creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @Schema(description = "")
  public Instant getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(Instant creationDate) {
    this.creationDate = creationDate;
  }

  public VaccinationInfoDto changeDate(Instant changeDate) {
    this.changeDate = changeDate;
    return this;
  }

   /**
   * Get changeDate
   * @return changeDate
  **/
  @Schema(description = "")
  public Instant getChangeDate() {
    return changeDate;
  }

  public void setChangeDate(Instant changeDate) {
    this.changeDate = changeDate;
  }

  public VaccinationInfoDto uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @Schema(description = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public VaccinationInfoDto vaccination(Vaccination vaccination) {
    this.vaccination = vaccination;
    return this;
  }

   /**
   * Get vaccination
   * @return vaccination
  **/
  @Schema(description = "")
  public Vaccination getVaccination() {
    return vaccination;
  }

  public void setVaccination(Vaccination vaccination) {
    this.vaccination = vaccination;
  }

  public VaccinationInfoDto vaccinationDoses(String vaccinationDoses) {
    this.vaccinationDoses = vaccinationDoses;
    return this;
  }

   /**
   * Get vaccinationDoses
   * @return vaccinationDoses
  **/
  @Schema(description = "")
  public String getVaccinationDoses() {
    return vaccinationDoses;
  }

  public void setVaccinationDoses(String vaccinationDoses) {
    this.vaccinationDoses = vaccinationDoses;
  }

  public VaccinationInfoDto firstVaccinationDate(Instant firstVaccinationDate) {
    this.firstVaccinationDate = firstVaccinationDate;
    return this;
  }

   /**
   * Get firstVaccinationDate
   * @return firstVaccinationDate
  **/
  @Schema(description = "")
  public Instant getFirstVaccinationDate() {
    return firstVaccinationDate;
  }

  public void setFirstVaccinationDate(Instant firstVaccinationDate) {
    this.firstVaccinationDate = firstVaccinationDate;
  }

  public VaccinationInfoDto lastVaccinationDate(Instant lastVaccinationDate) {
    this.lastVaccinationDate = lastVaccinationDate;
    return this;
  }

   /**
   * Get lastVaccinationDate
   * @return lastVaccinationDate
  **/
  @Schema(description = "")
  public Instant getLastVaccinationDate() {
    return lastVaccinationDate;
  }

  public void setLastVaccinationDate(Instant lastVaccinationDate) {
    this.lastVaccinationDate = lastVaccinationDate;
  }

  public VaccinationInfoDto vaccinationInfoSource(VaccinationInfoSource vaccinationInfoSource) {
    this.vaccinationInfoSource = vaccinationInfoSource;
    return this;
  }

   /**
   * Get vaccinationInfoSource
   * @return vaccinationInfoSource
  **/
  @Schema(description = "")
  public VaccinationInfoSource getVaccinationInfoSource() {
    return vaccinationInfoSource;
  }

  public void setVaccinationInfoSource(VaccinationInfoSource vaccinationInfoSource) {
    this.vaccinationInfoSource = vaccinationInfoSource;
  }

  public VaccinationInfoDto vaccineName(Vaccine vaccineName) {
    this.vaccineName = vaccineName;
    return this;
  }

   /**
   * Get vaccineName
   * @return vaccineName
  **/
  @Schema(description = "")
  public Vaccine getVaccineName() {
    return vaccineName;
  }

  public void setVaccineName(Vaccine vaccineName) {
    this.vaccineName = vaccineName;
  }

  public VaccinationInfoDto otherVaccineName(String otherVaccineName) {
    this.otherVaccineName = otherVaccineName;
    return this;
  }

   /**
   * Get otherVaccineName
   * @return otherVaccineName
  **/
  @Schema(description = "")
  public String getOtherVaccineName() {
    return otherVaccineName;
  }

  public void setOtherVaccineName(String otherVaccineName) {
    this.otherVaccineName = otherVaccineName;
  }

  public VaccinationInfoDto vaccineManufacturer(VaccineManufacturer vaccineManufacturer) {
    this.vaccineManufacturer = vaccineManufacturer;
    return this;
  }

   /**
   * Get vaccineManufacturer
   * @return vaccineManufacturer
  **/
  @Schema(description = "")
  public VaccineManufacturer getVaccineManufacturer() {
    return vaccineManufacturer;
  }

  public void setVaccineManufacturer(VaccineManufacturer vaccineManufacturer) {
    this.vaccineManufacturer = vaccineManufacturer;
  }

  public VaccinationInfoDto otherVaccineManufacturer(String otherVaccineManufacturer) {
    this.otherVaccineManufacturer = otherVaccineManufacturer;
    return this;
  }

   /**
   * Get otherVaccineManufacturer
   * @return otherVaccineManufacturer
  **/
  @Schema(description = "")
  public String getOtherVaccineManufacturer() {
    return otherVaccineManufacturer;
  }

  public void setOtherVaccineManufacturer(String otherVaccineManufacturer) {
    this.otherVaccineManufacturer = otherVaccineManufacturer;
  }

  public VaccinationInfoDto vaccineInn(String vaccineInn) {
    this.vaccineInn = vaccineInn;
    return this;
  }

   /**
   * Get vaccineInn
   * @return vaccineInn
  **/
  @Schema(description = "")
  public String getVaccineInn() {
    return vaccineInn;
  }

  public void setVaccineInn(String vaccineInn) {
    this.vaccineInn = vaccineInn;
  }

  public VaccinationInfoDto vaccineBatchNumber(String vaccineBatchNumber) {
    this.vaccineBatchNumber = vaccineBatchNumber;
    return this;
  }

   /**
   * Get vaccineBatchNumber
   * @return vaccineBatchNumber
  **/
  @Schema(description = "")
  public String getVaccineBatchNumber() {
    return vaccineBatchNumber;
  }

  public void setVaccineBatchNumber(String vaccineBatchNumber) {
    this.vaccineBatchNumber = vaccineBatchNumber;
  }

  public VaccinationInfoDto vaccineUniiCode(String vaccineUniiCode) {
    this.vaccineUniiCode = vaccineUniiCode;
    return this;
  }

   /**
   * Get vaccineUniiCode
   * @return vaccineUniiCode
  **/
  @Schema(description = "")
  public String getVaccineUniiCode() {
    return vaccineUniiCode;
  }

  public void setVaccineUniiCode(String vaccineUniiCode) {
    this.vaccineUniiCode = vaccineUniiCode;
  }

  public VaccinationInfoDto vaccineAtcCode(String vaccineAtcCode) {
    this.vaccineAtcCode = vaccineAtcCode;
    return this;
  }

   /**
   * Get vaccineAtcCode
   * @return vaccineAtcCode
  **/
  @Schema(description = "")
  public String getVaccineAtcCode() {
    return vaccineAtcCode;
  }

  public void setVaccineAtcCode(String vaccineAtcCode) {
    this.vaccineAtcCode = vaccineAtcCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VaccinationInfoDto vaccinationInfoDto = (VaccinationInfoDto) o;
    return Objects.equals(this.creationDate, vaccinationInfoDto.creationDate) &&
        Objects.equals(this.changeDate, vaccinationInfoDto.changeDate) &&
        Objects.equals(this.uuid, vaccinationInfoDto.uuid) &&
        Objects.equals(this.vaccination, vaccinationInfoDto.vaccination) &&
        Objects.equals(this.vaccinationDoses, vaccinationInfoDto.vaccinationDoses) &&
        Objects.equals(this.firstVaccinationDate, vaccinationInfoDto.firstVaccinationDate) &&
        Objects.equals(this.lastVaccinationDate, vaccinationInfoDto.lastVaccinationDate) &&
        Objects.equals(this.vaccinationInfoSource, vaccinationInfoDto.vaccinationInfoSource) &&
        Objects.equals(this.vaccineName, vaccinationInfoDto.vaccineName) &&
        Objects.equals(this.otherVaccineName, vaccinationInfoDto.otherVaccineName) &&
        Objects.equals(this.vaccineManufacturer, vaccinationInfoDto.vaccineManufacturer) &&
        Objects.equals(this.otherVaccineManufacturer, vaccinationInfoDto.otherVaccineManufacturer) &&
        Objects.equals(this.vaccineInn, vaccinationInfoDto.vaccineInn) &&
        Objects.equals(this.vaccineBatchNumber, vaccinationInfoDto.vaccineBatchNumber) &&
        Objects.equals(this.vaccineUniiCode, vaccinationInfoDto.vaccineUniiCode) &&
        Objects.equals(this.vaccineAtcCode, vaccinationInfoDto.vaccineAtcCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, changeDate, uuid, vaccination, vaccinationDoses, firstVaccinationDate, lastVaccinationDate, vaccinationInfoSource, vaccineName, otherVaccineName, vaccineManufacturer, otherVaccineManufacturer, vaccineInn, vaccineBatchNumber, vaccineUniiCode, vaccineAtcCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VaccinationInfoDto {\n");
    
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    changeDate: ").append(toIndentedString(changeDate)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    vaccination: ").append(toIndentedString(vaccination)).append("\n");
    sb.append("    vaccinationDoses: ").append(toIndentedString(vaccinationDoses)).append("\n");
    sb.append("    firstVaccinationDate: ").append(toIndentedString(firstVaccinationDate)).append("\n");
    sb.append("    lastVaccinationDate: ").append(toIndentedString(lastVaccinationDate)).append("\n");
    sb.append("    vaccinationInfoSource: ").append(toIndentedString(vaccinationInfoSource)).append("\n");
    sb.append("    vaccineName: ").append(toIndentedString(vaccineName)).append("\n");
    sb.append("    otherVaccineName: ").append(toIndentedString(otherVaccineName)).append("\n");
    sb.append("    vaccineManufacturer: ").append(toIndentedString(vaccineManufacturer)).append("\n");
    sb.append("    otherVaccineManufacturer: ").append(toIndentedString(otherVaccineManufacturer)).append("\n");
    sb.append("    vaccineInn: ").append(toIndentedString(vaccineInn)).append("\n");
    sb.append("    vaccineBatchNumber: ").append(toIndentedString(vaccineBatchNumber)).append("\n");
    sb.append("    vaccineUniiCode: ").append(toIndentedString(vaccineUniiCode)).append("\n");
    sb.append("    vaccineAtcCode: ").append(toIndentedString(vaccineAtcCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
