/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.61.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package iris.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets VaccineManufacturer
 */
public enum VaccineManufacturer {
  BIONTECH_PFIZER("BIONTECH_PFIZER"),
  MODERNA("MODERNA"),
  ASTRA_ZENECA("ASTRA_ZENECA"),
  JOHNSON_JOHNSON("JOHNSON_JOHNSON"),
  NOVAVAX("NOVAVAX"),
  SANOFI_GSK("SANOFI_GSK"),
  UNKNOWN("UNKNOWN"),
  OTHER("OTHER");

  private String value;

  VaccineManufacturer(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static VaccineManufacturer fromValue(String text) {
    for (VaccineManufacturer b : VaccineManufacturer.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
