#!/bin/bash

printf "\n  Build components and prepare release  \n\n"

# Get version number from version tag if this given
VERSION=`echo $1 | cut -d'v' -f2`
echo "version = $VERSION"

printf "\n  Build NGINX image  \n\n"
docker build -t inoeg/iris-client-nginx ./infrastructure/docker/nginx/

printf "\n  Build FE image  \n\n"
docker build -t inoeg/iris-client-frontend ./iris-client-fe/

printf "\n  Set version to POMs  \n\n"
# Set new version in pom.xml using mvn versions:set command
# These new pom.xml and changelog.md generated by @semantic-release/changelog
# will be commit it by @semantic-release/git
mvn versions:set -DnewVersion=$VERSION -DprocessAllModules=true

printf "\n  Build BFF image and JAR  \n\n"
# Package the new version and copy it to release folder
# These files will be upload to github by @semantic-release/github
mvn -B clean package spring-boot:repackage spring-boot:build-image -Dspring-boot.build-image.publish=false
mkdir release && cp ./iris-client-bff/target/*.jar release

printf "\n  Build FE ZIP  \n\n"
cd ./iris-client-fe
npm ci
export VUE_APP_API_BASE_URL="/api"
npm run build
cd dist && zip -qq -r ../../release/iris-client-fe-$VERSION.zip *

printf "\n  Create ZIP of deployment scripts and instructions  \n\n"
cd ../../infrastructure/deployment && zip -qq -r ../../release/deployment-$VERSION.zip *

cd ../../

printf "\n  COMPLETED: Build components and prepare release  \n\n"

#printenv 
