########################################################
# Intended for deployments on DEV server
#
# Provides IRIS client BFF and frontend together with a Postgresql database and NGINX
# IRIS frontend over NGINX: port = 443
########################################################
version: "3.4"
services:
  # Postgres Database
  postgres:
    image: postgres:13.2-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - psqldata_iris:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "psql",
          "-U",
          "${POSTGRES_USER}",
          "-c",
          "SELECT 1;",
          "${POSTGRES_USER}",
        ]
      interval: 15s
      timeout: 3s
      retries: 4
      start_period: 30s

  # IRIS Client backend for frontend (autoupdated by watchtower)
  iris-client:
    image: inoeg/iris-client-bff:${CLIENT_VERSION}
    expose:
      - 8092
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_USER}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      IRIS_SERVER_ADDRESS:
      IRIS_SERVER_PORT:
      SECURITY_JWT_JWT_SHARED_SECRET:
      HTTP_CLIENT_PROXY_HOST:
      HTTP_CLIENT_PROXY_PORT:
      HTTP_CLIENT_PROXY_SCHEME:
      EPS_CLIENT_EPS_CLIENT_URL: https://eps:5556/jsonrpc
      EPS_CLIENT_PROXY_CLIENT_URL: https://private-proxy-1:7766/jsonrpc
      PROXY_SERVICE_TARGET_SUBDOMAIN: proxy.dev.test-gesundheitsamt.de
      IRIS_CLIENT_BASEPATH: https://iris-frontend:28080
      IRIS_BACKEND-SERVICE_ENDPOINT: ls-1
      SPRING_MAIL_PROPERTIES_RECIPIENT_CASE_DATA_RECEIVED_NAME: "Tester"
      SPRING_MAIL_PROPERTIES_RECIPIENT_CASE_DATA_RECEIVED_EMAIL: "tester@iris-gateway.de"
      SPRING_MAIL_PROPERTIES_RECIPIENT_EVENT_DATA_RECEIVED_NAME: "Tester"
      SPRING_MAIL_PROPERTIES_RECIPIENT_EVENT_DATA_RECEIVED_EMAIL: "tester@iris-gateway.de"
      EXT_APP_DW_BASEURL: https://staging.digitales-wartezimmer.org/
      SECURITY_AUTH_DB_ADMIN_USER_NAME:
      SECURITY_AUTH_DB_ADMIN_USER_PASSWORD:
      SERVER_ERROR_INCLUDE-MESSAGE: ALWAYS
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "/cnb/lifecycle/launcher java -cp /workspace/BOOT-INF/classes:/workspace/BOOT-INF/lib/* iris.tools.HealthChecker || exit 1"
      interval: 20s
      timeout: 3s
      retries: 2
      start_period: 10s

  # IRIS Client Frontend (autoupdated by watchtower)
  iris-frontend:
    image: inoeg/iris-client-frontend:${CLIENT_VERSION}
    expose:
      - 28080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      SORMAS_SIDECAR_BASE_URL: /api
      CSV_EXPORT_STANDARD_ATOMIC_ADDRESS: "true"
    restart: unless-stopped
    depends_on:
      iris-client:
        condition: service_healthy

  eps:
    image: inoeg/eps:${EPS_VERSION}
    expose:
      - 4446
      - 5556
    depends_on:
      - iris-client
    volumes:
      - ${LOCAL_MOUNT_DIR}/settings:/app/settings
    environment:
      - EPS_SETTINGS=settings/roles/hd-1
    command: ["--level", "debug", "server", "run"]

  # Reverse Proxy
  nginx:
    image: inoeg/iris-client-nginx:develop
    ports:
      - ${NGINX_PORT}:443
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      IRIS_CLIENT_DOMAIN:
      IRIS_CLIENT_DOMAIN_CERT:
      IRIS_CLIENT_DOMAIN_CERT_KEY:
    volumes:
      - ${LOCAL_MOUNT_DIR}/conf:/etc/iris
      - ${LOCAL_MOUNT_DIR}/nginx:/etc/nginx/templates
    depends_on:
      - iris-client
      - iris-frontend

  private-proxy:
    image: inoeg/proxy:${EPS_VERSION}
    expose:
      - 5545
      - 8877
    volumes:
      - ${LOCAL_MOUNT_DIR}/settings:/app/settings
      - ${LOCAL_MOUNT_DIR}/private-proxy-db:/private-proxy
    environment:
      - PROXY_SETTINGS=settings/roles/private-proxy-1
      - MOUNT_POINTS=/app/settings,/private-proxy
    command: [ "--level", "trace", "run", "private" ]

  private-proxy-1:
    image: inoeg/eps:${EPS_VERSION}
    expose:
      - 7766
      - 7776
    volumes:
      - ${LOCAL_MOUNT_DIR}/settings:/app/settings
    environment:
      - EPS_SETTINGS=settings/roles/private-proxy-eps-1
    command: [ "--level", "trace", "server", "run" ]

volumes:
  psqldata_iris:
