/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.61.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package iris.sormas.client.api;

import iris.sormas.client.model.CampaignFormDataDto;
import iris.sormas.client.model.PushResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CampaignFormDataControllerApi
 */
@Ignore
public class CampaignFormDataControllerApiTest {

    private final CampaignFormDataControllerApi api = new CampaignFormDataControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCampaignFormDataTest() {
        Long since = null;
        List<CampaignFormDataDto> response = api.getAllCampaignFormData(since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUuids3Test() {
        List<String> response = api.getAllUuids3();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByUuids4Test() {
        List<String> body = null;
        List<CampaignFormDataDto> response = api.getByUuids4(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCampaignFormDataTest() {
        List<CampaignFormDataDto> body = null;
        List<PushResult> response = api.postCampaignFormData(body);

        // TODO: test validations
    }
}
