/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.61.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package iris.sormas.client.api;

import iris.sormas.client.model.CustomizableEnumValueDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomizableEnumValueControllerApi
 */
@Ignore
public class CustomizableEnumValueControllerApiTest {

    private final CustomizableEnumValueControllerApi api = new CustomizableEnumValueControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCustomizableEnumValuesTest() {
        Long since = null;
        List<CustomizableEnumValueDto> response = api.getAllCustomizableEnumValues(since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUuids10Test() {
        List<String> response = api.getAllUuids10();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByUuids13Test() {
        List<String> body = null;
        List<CustomizableEnumValueDto> response = api.getByUuids13(body);

        // TODO: test validations
    }
}
