/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.61.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package iris.sormas.client.api;

import iris.sormas.client.model.FacilityDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FacilityControllerApi
 */
@Ignore
public class FacilityControllerApiTest {

    private final FacilityControllerApi api = new FacilityControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllByRegionTest() {
        String regionUuid = null;
        Long since = null;
        List<FacilityDto> response = api.getAllByRegion(regionUuid, since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUuids13Test() {
        List<String> response = api.getAllUuids13();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllWithoutRegionTest() {
        Long since = null;
        List<FacilityDto> response = api.getAllWithoutRegion(since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByUuids18Test() {
        List<String> body = null;
        List<FacilityDto> response = api.getByUuids18(body);

        // TODO: test validations
    }
}
