########################################################
# the IRIS NGINX as reverse proxy of the complete compose
# NGINX: port = ${IRIS_CLIENT_PORT} (Default = 443)
########################################################
version: "3.9"
services:
  nginx:
    image: inoeg/iris-client-nginx:${CLIENT_VERSION:?}
    ports:
      - ${IRIS_CLIENT_PORT:-443}:443
    environment:
      IRIS_CLIENT_DOMAIN: ${IRIS_CLIENT_DOMAIN:?}
      IRIS_CLIENT_DOMAIN_CERT: ${IRIS_CLIENT_DOMAIN_CERT:?}
      IRIS_CLIENT_DOMAIN_CERT_KEY: ${IRIS_CLIENT_DOMAIN_CERT_KEY:?}
    volumes:
      - ./certs/nginx:/etc/iris
    depends_on:
      - iris-client
      - iris-frontend
    restart: unless-stopped
