########################################################
# provides a PostgreSQL database
# DB: login = ${POSTGRES_USER}:${POSTGRES_PASSWORD}; hostname = postgres; port = 5432; volume = psqldata_iris
########################################################
version: "3.9"
services:
  postgres:
    image: postgres:13.2-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    volumes:
      - psqldata_iris:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "psql",
          "-U",
          "${POSTGRES_USER}",
          "-c",
          "SELECT 1;",
          "${POSTGRES_USER}",
        ]
      interval: 15s
      timeout: 3s
      retries: 4
      start_period: 30s
    restart: unless-stopped

volumes:
  psqldata_iris:
