########################################################
# provides Watchtower for auto-update of the other containers 
# sets the labels to the relevant services to enable auto-update
# polling all 60s
########################################################
version: "3.9"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # for Docker on Windows hosts - untested!
    # https://stackoverflow.com/questions/57466568/how-do-you-mount-the-docker-socket-on-windows
    #      - //var/run/docker.sock://var/run/docker.sock
    environment:
      TZ: Europe/Berlin
      WATCHTOWER_SCHEDULE: 0 0 3 * * *
      WATCHTOWER_NO_PULL: "true"
    restart: unless-stopped
