########################################################
# Intended for deployments at the health departments
# 
# Provides IRIS client BFF and frontend together with an NGINX. Uses an externally provided postgres database.
# IRIS frontend over NGINX: port = 443
########################################################
version: '3.4'
services:


  # IRIS Client backend for frontend
  iris-client:
    image: inoeg/iris-client-sormas-sidecar:0.2.0-rc.1
    expose:
      - 8092
    ports: 
      - 8092:8092
    environment: 
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      IRIS_SERVER_ADDRESS:
      IRIS_SERVER_PORT:
      SECURITY_JWT_JWT_SHARED_SECRET:
      HTTP_CLIENT_PROXY_HOST:
      HTTP_CLIENT_PROXY_PORT:
      HTTP_CLIENT_PROXY_SCHEME:
    restart: unless-stopped

  # IRIS Client Frontend
  iris-frontend:
    image: inoeg/iris-client-frontend:0.2.0-rc.1
    expose:
      - 28080
    environment: 
      SORMAS_SIDECAR_BASE_URL: /api
    ports: 
      - 28080:28080
    restart: unless-stopped
    depends_on:
      - iris-client

  # Reverse Proxy
  nginx:
    image: inoeg/iris-client-nginx:0.2.0-rc.1
    ports:
      - 443:443
    environment: 
      IRIS_CLIENT_DOMAIN:
      IRIS_CLIENT_DOMAIN_CERT:
      IRIS_CLIENT_DOMAIN_CERT_KEY:
    volumes:
      - ./conf:/etc/iris
    depends_on:
      - iris-client
      - iris-frontend
  
volumes:
  psqldata_iris: 
