definitions:
  CA_FILES:
    &CA_FILES
    - "/$DIR/../../../../../ca/live/root-x1.crt"
    - "/$DIR/../../../../../ca/live/root-x2.crt"
    - "/$DIR/../../../../../ca/live/D-TRUST_Limited_Basic_Combined.pem"
  CERT_FILE: &CERT_FILE "/$DIR/../../../certs/$EPS_CLIENT_CERT"
  KEY_FILE: &KEY_FILE "/$DIR/../../../certs/$EPS_CLIENT_CERT_KEY"
  CA_INTERMEDIATE_FILES:
    &CA_INTERMEDIATE_FILES
    - "/$DIR/../../../../../ca/live/inter-r1.crt"
    - "/$DIR/../../../../../ca/live/inter-r2.crt"
  SD_ENDPOINTS: &SD_ENDPOINTS [ "https://prod.iris-gateway.de:32324/jsonrpc" ]
  SD_SERVER_NAME: &SD_SERVER_NAME [ "service-directory-production-1" ]

vars:
  EPS_OP:
    source: env
    variable: EPS_OP
    type: string
  EPS_CLIENT_CERT:
    source: env
    variable: EPS_CLIENT_CERT
    type: string
  EPS_CLIENT_CERT_KEY:
    source: env
    variable: EPS_CLIENT_CERT_KEY
    type: string
  PROXY_URL:
   source: env
   variable: PROXY_URL
   type: string
  IRIS_CLIENT_BFF_ENDPOINT:
    source: env
    variable: IRIS_CLIENT_BFF_ENDPOINT
    type: string


name: "$EPS_OP"
# IRIS Service directory. It provides information about IRIS participants such as connected Apps and locations of IRIS central services. 
directory:
  type: api
  settings:
    jsonrpc_client:
      proxy_url: "$PROXY_URL"
      tls:
        certificate_file: *CERT_FILE
        key_file: *KEY_FILE
        ca_certificate_files: *CA_FILES
    ca_certificate_files: *CA_FILES
    ca_intermediate_certificate_files: *CA_INTERMEDIATE_FILES
    endpoints: *SD_ENDPOINTS
    server_names: *SD_SERVER_NAME

channels: # defines all the channels that we want to open when starting the server
  - name: main JSON-RPC client # creates outgoing JSONRPC connections to deliver and receive messages
    type: jsonrpc_client
    settings:
      endpoint: "$IRIS_CLIENT_BFF_ENDPOINT"
  - name: main gRPC server # accepts incoming gRPC connections to deliver and receive messages
    type: grpc_server
    settings:
      bind_address: "0.0.0.0:8888"
      tls:
        ca_certificate_files: *CA_FILES
        certificate_file: *CERT_FILE
        key_file: *KEY_FILE
  - name: main gRPC client # creates outgoing gRPC connections to deliver and receive messages
    type: grpc_client
    settings:
      tls:
        ca_certificate_files: *CA_FILES
        certificate_file: *CERT_FILE
        key_file: *KEY_FILE
  - name: main JSON-RPC server # accepts incoming JSONRPC connections to deliver and receive messages
    type: jsonrpc_server
    settings:
      bind_address: "0.0.0.0:5556"
      tls:
        ca_certificate_files: *CA_FILES
        certificate_file: *CERT_FILE
        key_file: *KEY_FILE
        verify_client: false
