/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.55.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.healthIMIS.sormas.client.api;

import de.healthIMIS.sormas.client.model.CaseDataDto;
import de.healthIMIS.sormas.client.model.CasePersonDto;
import de.healthIMIS.sormas.client.model.PushResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CaseControllerApi
 */
@Ignore
public class CaseControllerApiTest {

    private final CaseControllerApi api = new CaseControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCasesTest() {
        Long since = null;
        List<CaseDataDto> response = api.getAllCases(since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUuids5Test() {
        List<String> response = api.getAllUuids5();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getArchivedUuidsSinceTest() {
        Long since = null;
        List<String> response = api.getArchivedUuidsSince(since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByUuids6Test() {
        List<String> body = null;
        List<CaseDataDto> response = api.getByUuids6(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeletedUuidsSinceTest() {
        Long since = null;
        List<String> response = api.getDeletedUuidsSince(since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDuplicatesTest() {
        CasePersonDto body = null;
        List<CasePersonDto> response = api.getDuplicates(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCasesTest() {
        List<CaseDataDto> body = null;
        List<PushResult> response = api.postCases(body);

        // TODO: test validations
    }
}
