private:
  name: private-proxy-gotham
  datastore:
    type: file
    settings:
      filename: /private-proxy-gotham/private-proxy-announcements.db
  bind_address: 0.0.0.0:5546
  internal_endpoint:
    address: "iris-client:8092/data-submission-rpc"
    tls:
      verify_client: false
      server_name: proxy2.dev.test-gesundheitsamt.de
      ca_certificate_files: [ "/$DIR/../../certs/root.crt" ]
      certificate_file: "/$DIR/../../certs/internal-server-2.crt"
      key_file: "/$DIR/../../certs/internal-server-2.key"
    #verify_service_call: true
  jsonrpc_client:
    endpoint: https://private-proxy-1:7766/jsonrpc
    server_name: private-proxy-gotham
    tls:
      ca_certificate_files: [ "/$DIR/../../certs/root.crt" ]
      certificate_file: "/$DIR/../../certs/private-proxy-gotham.crt"
      key_file: "/$DIR/../../certs/private-proxy-gotham.key"
  jsonrpc_server: # the JSON-RPC server that the EPS server uses for communication
    bind_address: 0.0.0.0:8877

