definitions:
  CA_FILES:
    &CA_FILES
    - "/$DIR/../../../../../ca/staging/IRIS-CA-Staging.crt"
    - "/$DIR/../../../../../ca/staging/D-TRUST_Limited_Basic_Test_Combined.pem"
  CERT_FILE: &CERT_FILE "/$DIR/../../../certs/$PROXY_CLIENT_CERT"
  KEY_FILE: &KEY_FILE "/$DIR/../../../certs/$PROXY_CLIENT_CERT_KEY"
  CA_INTERMEDIATE_FILES:
    &CA_INTERMEDIATE_FILES
    []
  SD_ENDPOINTS: &SD_ENDPOINTS [ "https://test.iris-gateway.de:32324/jsonrpc" ]
  SD_SERVER_NAME: &SD_SERVER_NAME [ "sd-1" ]

vars:
  PROXY_OP:
    source: env
    variable: PROXY_OP
    type: string
  PROXY_CLIENT_CERT:
    source: env
    variable: PROXY_CLIENT_CERT
    type: string
  PROXY_CLIENT_CERT_KEY:
    source: env
    variable: PROXY_CLIENT_CERT_KEY
    type: string  
  PROXY_URL:
   source: env
   variable: PROXY_URL
   type: string
  PRIVATE_PROXY_ENDPOINT:
   source: env
   variable: PRIVATE_PROXY_ENDPOINT
   type: string

name: "$PROXY_OP"
directory:
  type: api
  settings:
    jsonrpc_client:
      proxy_url: "$PROXY_URL"
      tls:
        certificate_file: *CERT_FILE
        key_file: *KEY_FILE
        ca_certificate_files: *CA_FILES
    ca_certificate_files: *CA_FILES
    endpoints: *SD_ENDPOINTS
    server_names: *SD_SERVER_NAME
channels: # defines all the channels that we want to open when starting the server
  - name: main gRPC server # accepts incoming gRPC connections to deliver and receive messages
    type: grpc_server
    settings:
      bind_address: "0.0.0.0:7776"
      tls:
        ca_certificate_files: *CA_FILES
        certificate_file: *CERT_FILE
        key_file: *KEY_FILE
  - name: main JSON-RPC client # creates outgoing JSONRPC connections to deliver and receive messages
    type: jsonrpc_client
    settings:
      endpoint: "$PRIVATE_PROXY_ENDPOINT"
  - name: main gRPC client # creates outgoing gRPC connections to deliver and receive messages
    type: grpc_client
    settings:
      tls:
        ca_certificate_files: *CA_FILES
        certificate_file: *CERT_FILE
        key_file: *KEY_FILE
        server_name: "$PROXY_OP"
  - name: main JSON-RPC server # accepts incoming JSONRPC connections to deliver and receive messages
    type: jsonrpc_server
    settings:
      bind_address: "0.0.0.0:7766"
      tls:
        ca_certificate_files: *CA_FILES
        certificate_file: *CERT_FILE
        key_file: *KEY_FILE
        verify_client: false
