vars:
  PROXY_OP:
    source: env
    variable: PROXY_OP
    type: string
  PROXY_CLIENT_CERT:
    source: env
    variable: PROXY_CLIENT_CERT
    type: string
  PROXY_CLIENT_CERT_KEY:
    source: env
    variable: PROXY_CLIENT_CERT_KEY
    type: string    
  PROXY_DOMAIN:     
    source: env
    variable: PROXY_DOMAIN
    type: string
  PROXY_TLS_CERT:     
    source: env
    variable: PROXY_TLS_CERT
    type: string
  PROXY_TLS_CERT_KEY:     
    source: env
    variable: PROXY_TLS_CERT_KEY
    type: string
  IRIS_CLIENT_BFF_ENDPOINT:     
    source: env
    variable: IRIS_CLIENT_BFF_ENDPOINT
    type: string
  PRIVATE_PROXY_EPS_ENDPOINT:     
    source: env
    variable: PRIVATE_PROXY_EPS_ENDPOINT
    type: string
    

private:
  name: "$PROXY_OP"
  database_file: ./db/private-proxy-announcements.db
  bind_address: 0.0.0.0:5545
  internal_endpoint:
    address: "$IRIS_CLIENT_BFF_ENDPOINT"
    tls:
      verify_client: false
      server_name: "$PROXY_DOMAIN"
      ca_certificate_files: 
        - "$DIR/../../../../../ca/staging/IRIS-CA-Staging.crt"
        - "$DIR/../../../../../ca/staging/D-TRUST_Limited_Basic_Test_Combined.pem"
      certificate_file: "$DIR/../../../certs/$PROXY_TLS_CERT"
      key_file: "$DIR/../../../certs/$PROXY_TLS_CERT_KEY"

  jsonrpc_client:
    endpoint: "$PRIVATE_PROXY_EPS_ENDPOINT"
    tls:
      server_name: "$PROXY_OP"
      ca_certificate_files: 
        - "$DIR/../../../../../ca/staging/IRIS-CA-Staging.crt"
        - "$DIR/../../../../../ca/staging/D-TRUST_Limited_Basic_Test_Combined.pem"
      certificate_file: "$DIR/../../../certs/$PROXY_CLIENT_CERT"
      key_file: "$DIR/../../../certs/$PROXY_CLIENT_CERT_KEY"
  jsonrpc_server: # the JSON-RPC server that the EPS server uses for communication
    bind_address: 0.0.0.0:8877