
vars:
  PROXY_OP:
    source: env
    variable: PROXY_OP
    type: string
  PROXY_CLIENT_CERT:
    source: env
    variable: PROXY_CLIENT_CERT
    type: string
  PROXY_CLIENT_CERT_KEY:
    source: env
    variable: PROXY_CLIENT_CERT_KEY
    type: string  
  EPS_SD_ENDPOINT:
    source: env
    variable: EPS_SD_ENDPOINT
    type: string        
  EPS_SD_NAME:
    source: env
    variable: EPS_SD_NAME
    type: string      
  PROXY_URL:
   source: env
   variable: PROXY_URL
   type: string
  PRIVATE_PROXY_ENDPOINT:
   source: env
   variable: PRIVATE_PROXY_ENDPOINT
   type: string


name: "$PROXY_OP"
directory:
  type: api
  settings:
    jsonrpc_client:
      proxy_url: "$PROXY_URL"
      tls:
        certificate_file: "/$DIR/../../../certs/$PROXY_CLIENT_CERT"
        key_file: "/$DIR/../../../certs/$PROXY_CLIENT_CERT_KEY"
        ca_certificate_files: 
          - "/$DIR/../../../ca/live/root-x1.crt"
          - "/$DIR/../../../ca/live/root-x2.crt"
          - "/$DIR/../../../ca/live/D-TRUST_Limited_Basic_Combined.pem"
    ca_certificate_files: 
      - "/$DIR/../../../ca/live/root-x1.crt"
      - "/$DIR/../../../ca/live/root-x2.crt"
      - "/$DIR/../../../ca/live/D-TRUST_Limited_Basic_Combined.pem"
    ca_intermediate_certificate_files:
      - "/$DIR/../../../ca/live/inter-r1.crt"
      - "/$DIR/../../../ca/live/inter-r2.crt"
    endpoints: [ "$EPS_SD_ENDPOINT" ]
    server_names: [ "$EPS_SD_NAME" ]
channels: # defines all the channels that we want to open when starting the server
  - name: main gRPC server # accepts incoming gRPC connections to deliver and receive messages
    type: grpc_server
    settings:
      bind_address: "0.0.0.0:7776"
      tls:
        ca_certificate_files: 
          - "/$DIR/../../../ca/live/root-x1.crt"
          - "/$DIR/../../../ca/live/root-x2.crt"
          - "/$DIR/../../../ca/live/D-TRUST_Limited_Basic_Combined.pem"
        certificate_file: "/$DIR/../../../certs/$PROXY_CLIENT_CERT"
        key_file: "/$DIR/../../../certs/$PROXY_CLIENT_CERT_KEY"
  - name: main JSON-RPC client # creates outgoing JSONRPC connections to deliver and receive messages
    type: jsonrpc_client
    settings:
      endpoint: "$PRIVATE_PROXY_ENDPOINT"
  - name: main gRPC client # creates outgoing gRPC connections to deliver and receive messages
    type: grpc_client
    settings:
      tls:
        ca_certificate_files: 
          - "/$DIR/../../../ca/live/root-x1.crt"
          - "/$DIR/../../../ca/live/root-x2.crt"
          - "/$DIR/../../../ca/live/D-TRUST_Limited_Basic_Combined.pem"
        certificate_file: "/$DIR/../../../certs/$PROXY_CLIENT_CERT"
        key_file: "/$DIR/../../../certs/$PROXY_CLIENT_CERT_KEY"
        server_name: "$PROXY_OP"
  - name: main JSON-RPC server # accepts incoming JSONRPC connections to deliver and receive messages
    type: jsonrpc_server
    settings:
      bind_address: "0.0.0.0:7766"
      tls:
        ca_certificate_files: 
          - "/$DIR/../../../ca/live/root-x1.crt"
          - "/$DIR/../../../ca/live/root-x2.crt"
          - "/$DIR/../../../ca/live/D-TRUST_Limited_Basic_Combined.pem"
        certificate_file: "/$DIR/../../../certs/$PROXY_CLIENT_CERT"
        key_file: "/$DIR/../../../certs/$PROXY_CLIENT_CERT_KEY"
        verify_client: false