name: Client Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  determine_tag:
    name: Determines Image Tag
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
      image_json: ${{ steps.meta.outputs.json }}
    steps:
      - name: Determines Image Tag
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: inoeg/iris-client-bff,inoeg/iris-client-frontend
  
  skip_check_bff:
    name: Determines BFF Job skipping
    continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          skip_after_successful_duplicate: 'false'
          concurrent_skipping: 'never'
          cancel_others: 'true'
          paths: '[".github/workflows/bff_develop.yml", "iris-client-bff/**", "!**/Readme.md"]'
  