name: Build and pre-release

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 12.x

      - name: Install dependencies
        run: npm ci
        working-directory: ./iris-client-fe

      - name: Build
        run: npm run build
        env:
          VUE_APP_API_BASE_URL: /api
        working-directory: ./iris-client-fe

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r iris-client-fe-${{ steps.get_version.outputs.VERSION }}.zip iris-client-fe/dist/

      - name: Cache local Maven repository
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: build Jars and Images
        run: mvn -B clean package spring-boot:repackage spring-boot:build-image -Dspring-boot.build-image.publish=true -Dversion.tag=${{ steps.get_version.outputs.VERSION }}
        env:
          GIT_TAG: ${{ steps.get_version.outputs.VERSION }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PW: ${{ secrets.DOCKER_HUB_PW }}

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r docker-compose-deployment-${{ steps.get_version.outputs.VERSION }}.zip infrastructure/deployment

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            **/target/*${{ steps.get_version.outputs.VERSION }}.jar
            **/docker-compose-deployment-${{ steps.get_version.outputs.VERSION }}.zip
            **/iris-client-fe-${{ steps.get_version.outputs.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
