name: Trivy Container Scan

on:
  workflow_call:
    inputs:
      image-refs:
        description: 'Stringified JSON array listing target image references'
        required: true
        type: string

jobs:
  container_scan:
    name: Scan and Publish
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        image-ref: ${{fromJson(inputs.image-refs)}}
    
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ matrix.image-ref }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
