name: FE Develop

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Tag that will be added to the image name'
        required: true
        type: string
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PW:
        required: true

jobs:
  build_and_push:
    name: Build and push to docker.io
    runs-on: ubuntu-latest
    
    env:
      tags: inoeg/iris-client-frontend:${{ inputs.image_tag }}
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}

      - name: Build and push to docker.io
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./iris-client-fe/
          tags: ${{ env.tags }}
          push: true
          build-args: |
            VUE_APP_VERSION_ID=${{ env.tags }}
            VUE_APP_BUILD_ID=${{ github.sha }}
          labels: |
            iris.client-fe.image.revision=${{ github.sha }}
